[app]
  title = "æ•¸ç†ç­†è¨˜"

[header]
  [header.title]
    logo = ""
    name = "æ•¸ç†ç­†è¨˜"
    pre = ""
    post = ""
    typeit = false
  themeChangeMode = "manual"

[footer]
  enable = true
  custom = "ä»¥å¤šèªè¨€è¨˜éŒ„é«˜ä¸­æ•¸å­¸èˆ‡è‡ªç„¶ç§‘å­¸ç­†è¨˜"
  hugo = true
  author = true

[sidebar]
  emoji = "ğŸ“˜"
  subtitle = "é«˜ä¸­æ•¸å­¸èˆ‡ç§‘å­¸æœ­è¨˜"

[page]
  toc = true
  math = true

[page.share]
  enable = true

[page.readingTime]
  enable = true

[page.lightgallery]
  enable = true

[page.code]
  copy = true

[page.comments]
  enable = false
