title: Ekuu ê 數理筆記
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
markdown: kramdown
future: true

kramdown:
  math_engine: mathjax
  
sass:
  style: compressed
  load_paths:
    - assets/css