title: Ekuu ê 數理筆記
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  
markdown: kramdown
future: true
theme: null

kramdown:
  math_engine: mathjax
show_downloads: false
timezone: Asia/Taipei
sass:
  style: compressed
  load_paths:
    - assets/css