title: Ekuu ê 數理筆記
description: 高中數學與物理的台文、中文對照筆記
author: ekuut
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: default
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
markdown: kramdown
kramdown:
  math_engine: mathjax
future: true
sass:
  style: compressed
  load_paths:
    - assets/css
timezone: Asia/Taipei
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      mathjax: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      mathjax: true
